export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_CARPARKS_START = 'FETCH_CARPARKS_START'
export const FETCH_CARPARKS_SUCCESS = 'FETCH_CARPARKS_SUCCESS';
export const FETCH_CARPARKS_FAIL = 'FETCH_CARPARKS_FAIL';

export const FETCH_PLATENUMBER_START = 'FETCH_PLATENUMBER_START';
export const FETCH_PLATENUMBER_SUCCESS = 'FETCH_PLATENUMBER_SUCCESS';
export const FETCH_PLATENUMBER_FAIL = 'FETCH_PLATENUMBER_FAIL';

export const SUBMIT_PLATENUMBER_START = 'SUBMIT_PLATENUMBER_START';
export const SUBMIT_PLATENUMBER_SUCCESS = 'SUBMIT_PLATENUMBER_SUCCESS';
export const SUBMIT_PLATENUMBER_FAIL = 'SUBMIT_PLATENUMBER_FAIL';