# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'
pod 'Firebase/Database'

target 'authfirebase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for authfirebase

  # target 'authfirebase-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  # pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'authfirebaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'authfirebase-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for authfirebase-tvOS

#   target 'authfirebase-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

